### ISSUE TITLE
can't launch our playbook with correct SSH key (format error)

### ISSUE THREAD

**Issue by ledufakademy** [rundeck-plugins/rundeck-ansible-plugin#302]
Failed to connect to the host via ssh: Load key \"/tmp/rundeck/ansible-runner1652830734805669756id_rsa\": invalid format

can you help ?

**Comment by ledufakademy** [comment]
bad parameter in Ansible plugins, it's works now.

**Comment by jricher2771** [comment]
I'm also facing this exact error, what parameter in the Ansible plugin was bad for you? Any help here would be great.

**Comment by Lusitaniae** [comment]
#metoo, I'm loading the key  from Key Storage

**Comment by Lusitaniae** [comment]
Found my solution at https://tech.davidfield.co.uk/rundeck-3-install-setup-and-an-example-project/

"Need to change from SSH to RSA format": 

`ssh-keygen -p -m PEM -f keyfile`
