### ISSUE TITLE
v5.3.0 - Error in vault password file loading

### ISSUE THREAD

**Issue by diginote** [rundeck-plugins/rundeck-ansible-plugin#370]
**Describe the bug**

Since v5.3.0 I get the error »Invalid vault password was provided from script (...)« on runnung ansible playbooks that use encrypted ansible vault variables. Running the playbook with ansible (without rundeck) works. I use Key storage for vault password and become method. 

**My Rundeck detail**

* Rundeck version: 5.3.0
* install type: docker
* OS Name/version: debian
* DB Type/version: mysql

**To Reproduce**

1. create a playbook with tasks that use encrypted variables with ansible vault
2. create job to run ansible playbook
2. run job and get decryption password for vault from key storage

**Expected behavior**
Rundeck job finishes without error like in v5.2.0 or before

**Additional context**
see the same error mentioned here: https://www.reddit.com/r/Rundeck/comments/1d1qwqm/error_after_uprade_to_530/

**Comment by ltamaster** [comment]
can you share the job definition (I don't need the playbook, just the ansible step settings)?
are you using an encrypted playbook or an encrypted extra vars file?

**Comment by tpegeot** [comment]
Hello,
I'm facing the same issue that was described on Reddit. 

```
[WARNING]: Error in vault password file loading (None): Invalid vault password was provided from script (/tmp/rundeck/ansible-
runner4503715887996482637ansible-script-vault-client.py
```

I attached the job definiton

[job definition.json](https://github.com/user-attachments/files/15514173/job.definition.json)

Thank you in advance

**Comment by diginote** [comment]
Here is my job definition 

[job_definition.json](https://github.com/user-attachments/files/15524647/job_definition.json)
